version: "3"
services:
  java-db:
    container_name: postgres-db
    image: postgres:15.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: CrisalisDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    mem_limit: "512m"
    mem_reservation: "128m"
    cpus: "0.5"

  pg-admin:
    user: root
    depends_on:
      - java-db
    container_name: pg-admin
    image: dpage/pgadmin4:6.17
    ports:
      - 8040:80
    environment:
      PGADMIN_DEFAULT_EMAIL: gestioncrisalis@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    mem_limit: "512m"
    mem_reservation: "128m"
    cpus: "0.5"

volumes:
  pgdata:
