name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.3.0
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}+${increment}"
      id: version
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        docker build -t $DOCKER_USER/gestion-crisalis:$NEW_VERSION .
        docker build -t $DOCKER_USER/gestion-crisalis:latest .
        
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        docker push $DOCKER_USER/gestion-crisalis:$NEW_VERSION
        docker push $DOCKER_USER/gestion-crisalis:latest
